import { LitElement, TemplateResult } from 'lit';
import { OscdTextButton } from '@omicronenergy/oscd-ui/button/OscdTextButton.js';
import { OscdFilledIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdFilledIconButton.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdEditorTemplateTextfield } from './components/OscdEditorTemplateTextfield.js';
import { OscdActionList } from '@omicronenergy/oscd-ui/action-list/OscdActionList.js';
import OscdSclDialogs from '@omicronenergy/oscd-scl-dialogs/OscdSclDialogs.js';
import type { CreateWizard, EditWizard } from '@omicronenergy/oscd-scl-dialogs/OscdSclDialogs.js';
declare const OscdEditorTemplate_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
/** An editor [[`plugin`]] for editing the `DataTypeTemplates` section. */
export default class OscdEditorTemplate extends OscdEditorTemplate_base {
    static scopedElements: {
        'oscd-text-button': typeof OscdTextButton;
        'oscd-filled-icon-button': typeof OscdFilledIconButton;
        'oscd-icon': typeof OscdIcon;
        'oscd-action-list': typeof OscdActionList;
        'oscd-editor-template-textfield': typeof OscdEditorTemplateTextfield;
        'oscd-scl-dialogs': typeof OscdSclDialogs;
    };
    /** The document being edited as provided to plugins by [[`OpenSCD`]]. */
    doc: XMLDocument;
    docName: string;
    docVersion: unknown;
    selectedLNodeType: Element | null | undefined;
    selectedDOType: Element | null | undefined;
    selectedDAType: Element | null | undefined;
    selectedEnumType: Element | null | undefined;
    get dataTypeTemplate(): Element | null;
    lNodeTypeDiff: boolean;
    lNodeTypeInputs?: OscdEditorTemplateTextfield[];
    doTypeDiff: boolean;
    doTypeInputs?: OscdEditorTemplateTextfield[];
    daTypeDiff: boolean;
    daTypeInputs?: OscdEditorTemplateTextfield[];
    enumTypeDiff: boolean;
    enumTypeInputs?: OscdEditorTemplateTextfield[];
    editDialog?: OscdSclDialogs;
    private onLNodeTypeInputChange;
    private onSaveLNodeType;
    private onDOTypeInputChange;
    private onSaveDOType;
    private onDATypeInputChange;
    private onSaveDAType;
    private onEnumTypeInputChange;
    private onSaveEnumType;
    handleCreateElement(createWizard: CreateWizard): Promise<void>;
    handleEditElement(editWizard: EditWizard): Promise<void>;
    handleCloseWizardEvent(): Promise<void>;
    private selectReferencedChild;
    private renderEnumTypeChildrenList;
    private renderEnumTypeList;
    private renderDATypeChildrenList;
    private renderDATypeList;
    private renderDOTypeChildrenList;
    private renderDOTypeList;
    private renderLNodeTypeChildrenList;
    private renderLNodeTypeList;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
export {};
